### ISSUE TITLE
系统Emoji删除的bug

### ISSUE THREAD

**Issue by LuKane** [bbbcode/KeyboardforChat#1]
当文本框内容为 :@"1111EmojiEmoji" 时,点击删除, 则文本框内容为:@"1111Emoji[特殊符号]" .
因为你在判断时,只是判断的是整个文本. 所以产生这样的bug
解决方案: 在ChatKeyBoard.m文件中 - (void)deleteBackward:(NSString *)text appendText:(NSString *)appendText方法内. else {  // 如果最后一个系统键盘输入的文字 下面加入一行代码 NSString *tempString = [text substringWithRange:NSMakeRange(text.length - 2, 2)]; 对tempString进行判断 就可以了

**Comment by bbbcode** [comment]
OK，@LuKane，感谢提出这个错误，目前代码一修复。
