### ISSUE TITLE
iOS11键盘bug

### ISSUE THREAD

**Issue by Gang679** [bbbcode/KeyboardforChat#31]
第一次输出框会出现 ，之后出现不了。

**Comment by Gang679** [comment]
![simulator screen shot - iphone 7 plus - 2017-09-29 at 16 48 41](https://user-images.githubusercontent.com/15606809/31008283-1e4e9c78-a536-11e7-9fb2-98f4cdd4f7ba.png)

**Comment by Gang679** [comment]
输入框出现不了

**Comment by bbbcode** [comment]
将代码第168行的判断改为begin.size.height>=0
